Repository AllenCellModeling/aicsimageio, pull requests merged in 2020-04, with the labels that each got.

#100 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#98 feature/writer-base-class-proposal
  aicsimageio/writers/writer.py
Labels: enhancement

#99 feature/read-leica-lif-files
  .gitignore
  README.md
  aicsimageio/aics_image.py
  aicsimageio/exceptions.py
  aicsimageio/readers/__init__.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/tests/readers/test_lif_reader.py
  aicsimageio/tests/test_aics_image.py
  scripts/download_test_resources.py
  scripts/upload_test_resources.py
  setup.py
Labels: enhancement

#108 admin/use-black-formatting
  .github/workflows/build-master.yml
  .github/workflows/test-and-lint.yml
  aicsimageio/aics_image.py
  aicsimageio/buffer_reader.py
  aicsimageio/dask_utils.py
  aicsimageio/exceptions.py
  aicsimageio/readers/arraylike_reader.py
  aicsimageio/readers/czi_reader.py
  aicsimageio/readers/default_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/readers/reader.py
  aicsimageio/readers/tiff_reader.py
  aicsimageio/tests/readers/test_arraylike_reader.py
  aicsimageio/tests/readers/test_czi_reader.py
  aicsimageio/tests/readers/test_default_reader.py
  aicsimageio/tests/readers/test_lif_reader.py
  aicsimageio/tests/readers/test_ome_tiff_reader.py
  aicsimageio/tests/readers/test_reader.py
  aicsimageio/tests/readers/test_tiff_reader.py
  aicsimageio/tests/test_aics_image.py
  aicsimageio/tests/test_dask_utils.py
  aicsimageio/tests/test_transforms.py
  aicsimageio/tests/writers/test_ome_tiff_writer.py
  aicsimageio/tests/writers/test_png_writer.py
  aicsimageio/tests/writers/transformation.py
  aicsimageio/transforms.py
  aicsimageio/writers/ome_tiff_writer.py
  aicsimageio/writers/png_writer.py
  setup.cfg
  setup.py
  tox.ini
Labels: admin

#109 feature/allow-sequence-in-get-data
  aicsimageio/aics_image.py
  aicsimageio/tests/test_transforms.py
  aicsimageio/transforms.py
Labels: enhancement
