Repository AllenCellModeling/aicsimageio, pull requests merged in 2021-06, with the labels that each got.

#246 feature/default-to-pixel-size-none
  aicsimageio/readers/czi_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/readers/reader.py
  aicsimageio/tests/image_container_test_utils.py
  aicsimageio/tests/readers/test_array_like_reader.py
  aicsimageio/tests/readers/test_default_reader.py
  aicsimageio/tests/readers/test_lif_reader.py
  aicsimageio/tests/readers/test_ome_tiff_reader.py
  aicsimageio/tests/readers/test_tiff_reader.py
  aicsimageio/tests/test_aics_image.py
  aicsimageio/tests/writers/test_ome_tiff_writer.py
  aicsimageio/types.py
  aicsimageio/writers/ome_tiff_writer.py
Labels: admin, bug, enhancement, v4

#247 bugfix/support-rgb-mosaic-czi
  aicsimageio/readers/czi_reader.py
Labels: bug

#248 admin/remove-dev-release-infra
  Makefile
  aicsimageio/__init__.py
  cookiecutter.yaml
  docs/GOVERNANCE.md
  setup.cfg
  setup.py
Labels: admin

#250 bugfix/coords-and-floating-point-math-and-czi-scene-naming
  Makefile
  aicsimageio/readers/czi_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/readers/reader.py
Labels: bug

#253 docs/fix-physical-pixel-sizes-type
  README.md
Labels: documentation

#256 docs/add-missing-czi-reading-to-mosaic-support
  README.md
Labels: documentation

#258 admin/add-doi
  README.md
Labels: admin, documentation

#261 admin/bump-aicspylibczi-dep-version
  aicsimageio/readers/czi_reader.py
  aicsimageio/readers/default_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/tiff_reader.py
  setup.py
Labels: admin

#265 fix channel_names array expansion test
  aicsimageio/tests/writers/test_ome_tiff_writer.py
  aicsimageio/writers/ome_tiff_writer.py
Labels: bug
