Repository AllenCellModeling/aicsimageio, pull requests merged in 2021-11, with the labels that each got.

#336 Map `bioformats` images with tiles in x-y dimension in `dask`
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/tests/readers/test_bioformats_reader.py
  scripts/TEST_RESOURCES_HASH.txt
Labels: enhancement

#347 feature/add-getitem-to-dimensions-object
  aicsimageio/dimensions.py
  aicsimageio/tests/test_dimensions.py
Labels: enhancement

#346 feature/add-stored-mm-indexer-function-to-glob-reader
  aicsimageio/readers/tiff_glob_reader.py
  aicsimageio/tests/readers/test_glob_reader.py
Labels: enhancement

#341 fix/only-close-biofiofile-on-exit-if-not-open-on-entry
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/tests/readers/test_bioformats_reader.py
  aicsimageio/tests/utils/test_dask_proxy.py
  aicsimageio/utils/dask_proxy.py
Labels: bug

#358 fix/pin-nd2-dependency
  setup.py
Labels: bug, admin
