Repository AllenCellModeling/aicsimageio, pull requests merged in 2021-03, with the labels that each got.

#211 feature/ome-tiff-writer-4
  aicsimageio/metadata/utils.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/tests/writers/test_ome_tiff_writer.py
  aicsimageio/writers/__init__.py
  aicsimageio/writers/ome_tiff_writer.py
Labels: enhancement

#212 feature/lif-reader
  aicsimageio/aics_image.py
  aicsimageio/dimensions.py
  aicsimageio/readers/__init__.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/readers/reader.py
  aicsimageio/readers/tiff_reader.py
  aicsimageio/tests/image_container_test_utils.py
  aicsimageio/tests/readers/test_lif_reader.py
  aicsimageio/tests/test_aics_image.py
  benchmarks/benchmark_image_containers.py
  scripts/TEST_RESOURCES_HASH.txt
  setup.py
Labels: enhancement

#215 feature/aicsimage-save
  .github/workflows/build-main.yml
  .github/workflows/test-and-lint.yml
  aicsimageio/aics_image.py
  aicsimageio/tests/test_aics_image.py
  aicsimageio/writers/ome_tiff_writer.py
  setup.py
  tox.ini
Labels: admin, enhancement

#216 admin/doc-updates
  Makefile
  README.md
  aicsimageio/aics_image.py
  aicsimageio/metadata/utils.py
  aicsimageio/readers/default_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/readers/reader.py
  aicsimageio/readers/tiff_reader.py
  aicsimageio/writers/ome_tiff_writer.py
  docs/CONTRIBUTING.md
  docs/conf.py
  docs/index.rst
Labels: admin, documentation

#221 admin/split-reader-deps
  .github/workflows/test-and-lint.yml
  README.md
  aicsimageio/aics_image.py
  aicsimageio/exceptions.py
  aicsimageio/formats.py
  aicsimageio/readers/__init__.py
  aicsimageio/readers/default_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/tests/readers/test_default_reader.py
  aicsimageio/tests/readers/test_lif_reader.py
  aicsimageio/tests/writers/test_timeseries_writer.py
  aicsimageio/tests/writers/test_two_d_writer.py
  aicsimageio/writers/__init__.py
  aicsimageio/writers/timeseries_writer.py
  aicsimageio/writers/two_d_writer.py
  setup.py
Labels: admin, documentation, enhancement
