Repository AllenCellModeling/aicsimageio, pull requests merged in 2021-05, with the labels that each got.

#229 feature/mosaic-tile-single-position-request-and-docs
  README.md
  aicsimageio/aics_image.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/reader.py
  aicsimageio/tests/readers/test_lif_reader.py
  aicsimageio/tests/test_aics_image.py
  setup.py
Labels: documentation

#232 admin/prep-for-v4-release
  .github/workflows/build-docs.yml
  .github/workflows/build-v3.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  README.md
Labels: admin, documentation

#233 admin/copy-v3 docs-to-static
  .github/workflows/build-docs.yml
  README.md
Labels: admin, documentation

#234 bugfix/setup-coords-for-stitched-lifs
  aicsimageio/readers/lif_reader.py
  aicsimageio/tests/readers/test_lif_reader.py
Labels: bug

#235 bugfix/always-use-synch-for-tiff-zarr-compute
  aicsimageio/readers/tiff_reader.py
  aicsimageio/tests/test_aics_image.py
Labels: bug

#236 admin/2021-dask-summit-presentation
  presentations/2021-dask-life-sciences/environment.yml
  presentations/2021-dask-life-sciences/presentation.ipynb
Labels: admin

#244 admin/4.0-release-prep-and-benchmark-upgrades
  .gitattributes
  asv.conf.json
  benchmarks/benchmark_chunk_sizes.py
  benchmarks/benchmark_image_containers.py
  benchmarks/benchmark_lib.py
  setup.py
Labels: admin, documentation, v4

#231 feature/czi-reader
  aicsimageio/readers/czi_reader.py
  aicsimageio/tests/readers/test_czi_reader.py
  aicsimageio/tests/test_aics_image.py
  benchmarks/benchmark_image_containers.py
  scripts/TEST_RESOURCES_HASH.txt
  scripts/download_test_resources.py
  setup.cfg
  setup.py
Labels: enhancement
