Repository AllenCellModeling/aicsimageio, pull requests merged in 2021-09, with the labels that each got.

#305 admin/add-custom-reader-addition-docs
  docs/CONTRIBUTING.md
Labels: documentation, admin

#308 Add .pre-commit-config.yaml
  .github/workflows/test-and-lint.yml
  .pre-commit-config.yaml
  aicsimageio/exceptions.py
  aicsimageio/readers/reader.py
  aicsimageio/writers/writer.py
  docs/CONTRIBUTING.md
  setup.cfg
  setup.py
  tox.ini
Labels: admin

#313 admin/add-test-resources-caching
  .github/workflows/build-main.yml
  .github/workflows/test-and-lint.yml
Labels: admin

#306 feature/bioformats-reader
  .github/workflows/build-main.yml
  .github/workflows/test-and-lint.yml
  README.md
  aicsimageio/formats.py
  aicsimageio/metadata/utils.py
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/tests/conftest.py
  aicsimageio/tests/readers/test_bioformats_reader.py
  aicsimageio/tests/test_aics_image.py
  aicsimageio/tests/utils/test_dask_proxy.py
  aicsimageio/utils/cached_property.py
  aicsimageio/utils/dask_proxy.py
  scripts/TEST_RESOURCES_HASH.txt
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#320 admin/loosen-version-pins
  setup.py
Labels: admin

#319 admin/exclude-benchmarks
  setup.py
Labels: admin

#318 bugfix/resolve-conflict-between-format-impls-and-determine-reader
  aicsimageio/aics_image.py
  aicsimageio/formats.py
  aicsimageio/tests/test_aics_image.py
  aicsimageio/types.py
  setup.py
Labels: bug

#324 docs/more-detailed-bioformats-install-instruction-on-error
  aicsimageio/readers/bioformats_reader.py
Labels: documentation
