Repository AllenCellModeling/aicsimageio, pull requests merged in 2022-05, with the labels that each got.

#397 admin/ship-mypy-type-annotations-drop-py37-add-py310-manage-test-dependencies-separate-for-each-tox-env
  .github/workflows/build-docs.yml
  .github/workflows/build-main.yml
  .github/workflows/test-and-lint.yml
  .pre-commit-config.yaml
  MANIFEST.in
  aicsimageio/py.typed
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/readers/czi_reader.py
  aicsimageio/readers/dv_reader.py
  aicsimageio/readers/tiff_glob_reader.py
  aicsimageio/tests/metadata/test_utils.py
  aicsimageio/tests/readers/extra_readers/__init__.py
  aicsimageio/tests/readers/extra_readers/test_bioformats_reader.py
  aicsimageio/tests/readers/extra_readers/test_czi_reader.py
  aicsimageio/tests/readers/extra_readers/test_default_reader.py
  aicsimageio/tests/readers/extra_readers/test_dv_reader.py
  aicsimageio/tests/readers/extra_readers/test_lif_reader.py
  aicsimageio/tests/readers/extra_readers/test_nd2_reader.py
  aicsimageio/tests/readers/extra_readers/test_ome_tiled_tiff_reader.py
  aicsimageio/tests/readers/test_array_like_reader.py
  aicsimageio/tests/readers/test_default_reader.py
  aicsimageio/tests/readers/test_glob_reader.py
  aicsimageio/tests/readers/test_ome_tiff_reader.py
  aicsimageio/tests/readers/test_tiff_reader.py
  aicsimageio/tests/test_aics_image.py
  aicsimageio/tests/utils/test_dask_proxy.py
  aicsimageio/tests/writers/extra_writers/__init__.py
  aicsimageio/tests/writers/extra_writers/test_timeseries_writer.py
  aicsimageio/tests/writers/extra_writers/test_two_d_writer.py
  aicsimageio/utils/cached_property.py
  aicsimageio/utils/dask_proxy.py
  asv.conf.json
  docs/CONTRIBUTING.md
  setup.py
  tox.ini
Labels: admin

#401 bugfix/pass-series-index-in-biofile-init
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/tests/image_container_test_utils.py
  aicsimageio/tests/readers/extra_readers/test_bioformats_reader.py
Labels: bug

#407 feature-and-admin/create-aicsimage-objects-with-fs-kwargs-and-remove-need-for-creds
  .github/workflows/build-docs.yml
  .github/workflows/build-main.yml
  .github/workflows/test-and-lint.yml
  README.md
  aicsimageio/aics_image.py
  aicsimageio/readers/bfio_reader.py
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/readers/czi_reader.py
  aicsimageio/readers/default_reader.py
  aicsimageio/readers/dv_reader.py
  aicsimageio/readers/lif_reader.py
  aicsimageio/readers/nd2_reader.py
  aicsimageio/readers/ome_tiff_reader.py
  aicsimageio/readers/reader.py
  aicsimageio/readers/tiff_glob_reader.py
  aicsimageio/readers/tiff_reader.py
  aicsimageio/tests/image_container_test_utils.py
  aicsimageio/tests/readers/test_ome_tiff_reader.py
  aicsimageio/tests/utils/test_io_utils.py
  aicsimageio/utils/io_utils.py
  aicsimageio/writers/ome_tiff_writer.py
  aicsimageio/writers/timeseries_writer.py
  aicsimageio/writers/two_d_writer.py
  setup.py
Labels: enhancement, admin

#402 admin/prepare-bioformats_reader-to-work-with-new-bioformats_jar-based-on-scyjava
  README.md
  aicsimageio/readers/bioformats_reader.py
  aicsimageio/tests/readers/extra_readers/test_bioformats_reader.py
  setup.cfg
  tox.ini
Labels: documentation, enhancement, admin
